# Project configuration
project:
  name: "Magnitsky Act Economic Impact Analysis"
  version: "1.0"
  author: "Pedro Schuves Marodin"
  
# Data sources configuration
data_sources:
  # Financial data
  yfinance:
    tickers:
      brazil:
        - "^BVSP"  # Ibovespa
        - "BRL=X"  # USD/BRL
        - "VIBOV11.SA"  # VIX Brasil
      global:
        - "^GSPC"  # S&P 500
        - "^IXIC"  # NASDAQ
        - "^VIX"   # CBOE VIX
      
  # Treasury data
  treasury:
    bonds:
      - "NTN-B"
      - "LTN"
      
# Analysis parameters
event_study:
  estimation_window: 120  # days before event
  event_window_start: -10  # days before event
  event_window_end: 30     # days after event
  
# Machine Learning
ml_config:
  clustering:
    algorithm: "kmeans"
    n_clusters: [2, 3, 4, 5]  # test different numbers
    features:
      - "CAR_magnitude"
      - "volatility_spike" 
      - "profile_score"
      - "country_risk"
      - "market_cap_gdp"
      
  prediction:
    algorithms:
      - "xgboost"
      - "lightgbm"
      - "random_forest"
    target: "CAR_5_days"
    
# Sentiment analysis
sentiment:
  sources:
    - "google_news"
    - "twitter"
    - "reddit"
  keywords:
    - "Alexandre de Moraes"
    - "Magnitsky Act"
    - "sanções"
    - "STF"
    - "Supremo"
